#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /var/lib/barnyard2 /var/log/barnyard2

        if getent passwd barnyard2 >/dev/null; then
            deluser --system barnyard2 || true
        fi
        if getent group barnyard2 >/dev/null; then
            delgroup --system barnyard2 || true
        fi
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
